version: '2.4'
services:
  jupyter:
    build: .
    env_file:
      - .env
    ports:
      - "${JUPYTER_PORT}:${JUPYTER_PORT}"
      - "${TENSORBOARD_PORT}:${TENSORBOARD_PORT}"
    command: bash -c "
        jupyter notebook --ip=0.0.0.0 --port=${JUPYTER_PORT} --allow-root &
        tensorboard --logdir=/logs --port=${TENSORBOARD_PORT} --bind_all --reload_multifile=true
      "
    volumes:
      - "${PROJECT_FOLDER}:/app"
      - "${PROJECT_FOLDER}data:/data"
      - "./logs/:/logs"
    mem_limit: "${DOCKER_MEM_LIMIT}"
    restart: always
